name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Run tests
        run: dotnet test test/Envoy.Control.Tests/Envoy.Control.Tests.csproj

      - name: Build with dotnet
        run: dotnet build src/Envoy.Control/Envoy.Control.csproj --configuration Release
